// <auto-generated />
namespace sourcecode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addSalesMan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSalesMan));
        
        string IMigrationMetadata.Id
        {
            get { return "201812041623062_addSalesMan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
